language: rust

rust:
  - nightly

env:
  matrix:
    - DOCKER_COMPOSE_VERSION=1.24.0
  global:
    - secure: KqfdP6kt7OGiUbDw3iX7AYuWcp7aK+kxDrL1pJ/KPMZ3AGvEPKfJ/mPJkHXG7TyRpWUZp+T2LIIVH2Vl0omJnJHweBhfCnoAwAs3rYrrdCPBI15uR2BA97TGyB1VsTynyj6cnl0sFZkCFaD6NF3txhZP7By2K9FUMmpM3AgsDqTOdz+g2kuvuHF1pgiSILesPJqslwFojBKDaK2NAh+rPWV1P7qLxhZyGKTtbnrMSsuIHisQaNNyWERjGpcw3kurLRwkNWv4xWKCf0bpdS7DK/gx+A4mkMsY3X/cJeS196yTg5l9GYvJXl9btZl60D5/HbbYECtsZSu4d0NnRddG4/hFbx3H+ZcMgx/kE97eq6LxJnN5J7QEqga98aKyco9mhg71t3w6BYMYSOBBxIJeadiyNTLkVmCWBqWTVTczsOsdKteZ+1pwFqqExn/+/O7wurek/Fc12MTrJKtwDYSms65lolpd6ZXV6fYWu8eB+4e47OnNwHhY7c2a1Hn3IHlWRJ/uECgUeiXz9Sjl0mwDUQFw5Zq1OczNUQAcLwTC3tMiJfADNWcaCsobdIfS4h6veDE4+4rIAwNhKQYBAF3RE07i7kA5tgGsFDvybrmIaN6YHDNyVZFLJ/X6/hAA6K+7zR+1+ZDU8R/BPak9WdDMr7ZNZNT+l81qiDVNz2DFqpI=
    - secure: G+vEe9Oh4xv6igUyzPX4juxTWI1FsOdkFIEoNiJo1NUcAr7/WKtgtI209AVAGm1GmiaNCnBEKsVFNUw63IG/05W/vkRr96OfYQszhdMNUHKxINHgUJiE82LA+82pEB1v76wVminN4bhh0/jFqsbZs1teMIK6SH0O7GusO/vSzPtbdQZ0NJYzEg1vmBup83rbvBsHqyuprR8BDhsE5V7yurTgKXQCZgzoI82WXm1GTpmglTjHO1uDzTryfQmuaVK0EvoWMaEVq8qbbGY4PTeuVz8B4icKooanEiAB+D0+8SmecVxeVSh5UhMP58Qmw5LR9MHOf6OXumr2bV6S8pweaA6vUjYRT1JyvXRJO7/5a8+ERLeHc/XMPaYZ3x7kqfA97aQ/HzOBtdqYv30VnZc7R8aMrGQDQueq/T3L7nI50zx0WBsANuyleyN/2wIFK0fhd/wnhaZUXOQcftDo9hmSVevdWiptuomj4DPANIz1XvOLtB+oC8Xbx+xklSfFnOzajSUVgGFatQjtD7foTUIY7bRwHPxfAMMNUXfxvkGCw5NxYmBLXZqRzvDh//kTCIYO2TP4mYVohI5QKP2unM6DlOrFOtkQ3WlJfxyocrrOtZxLHQHHEi4ut/W2+kJvWzfk7yZV/6xnvI4j0OqNHfQKuLsmaq7SsW6j6YgFTyECK9U=
    - secure: 1AxqQIlIAlYD1rZhvDbaObyCQgOIE41m4DPJ/iBD1Zy1akJI5hbp2Kw1sTL7wM2by/a6Kn+NaGfk1FtbzKA7dijYJrp4FOMVWwzo5ENf79IbGBwRaZiIApqrWY2dEwFZ5SqGAPeR134d3oPtesOCd5LR76x3eQoqHxECvGySYJiLrjtzMIzGFWZ2vS9vcaJV5FcGAxBVHxtiMAkUHoJnKK4kZs1dKh7x4xJmigDoURjuHUtxPOYrPb2huMtsmsOgfLUhqSX1QOl3TzSy3ZC2duSVkqlAZSMgMJcmjCESGpxJpH0PRzbVOaAZNms+d83JyxRcdPix40WYkXgxA//C8/r33zPzvLbDnZkg/T+ELHUkgXCPWlJvhcSKC8ZsT77rBYnmsFgyX1g3ycdVzIIDyuUfhNQ2RTQ1APqqiwtMfdKPhwijTOEaEVAZ0PedqZOEtci9gavu1c75/9L+3qvwgaOfey9NX/XdsP5VcGjp6IDPjBAvp1Pqf50W6enytTh3D9RS4Kkxr0AewZIboCKAKuLWqP1UY3PZoc01RJK9F/MqvOQJ99akgrKb7b8fpn1buVHQu1QEMFHAz6gT8hPo1eenSQQtxaTFnKjDbR7qOjXSGmBV80MPJiwWxd0yUw15znG0Kl9iRvzELG+eKM6rby7ijtppl7D+/TrsSL/Tg6s=

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install v10.5
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

cache: cargo

services:
  - docker

jobs:
  include:
    - stage: Test
      script: cargo test
    - stage: Deploy
      script: echo "deploying to Docker Hub..."
      deploy:
        provider: script
        script: bash deploy.sh
        on:
          branch: develop
