version: '3.6'
networks:
  default:
    external:
      name: webproxy
services:
  smmdb:
    build: .
    ports:
      - 3001:3001
    working_dir: /usr/src/app
    environment:
      - VIRTUAL_HOST=tarnadas.ddns.net
      - LETSENCRYPT_HOST=tarnadas.ddns.net
      - LETSENCRYPT_EMAIL=mreder1289@gmail.com
      - VIRTUAL_PORT=3001
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /home/root/mongodb/data:/data
    ports:
      - 27017:27017
#  mongorestore:
#    build: mongo
#    links:
#      - mongodb
#    depends_on:
#      - mongodb
  

