version: "3.6"
services:
  smmdb-api-build:
    build:
      context: .
      dockerfile: ./src/rust/DockerfileBuild
      cache_from:
        - tarnadas/smmdb-api-build
    image: tarnadas/smmdb-api-build
