version: '3.6'
services:
  smmdb:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data:/data
    ports:
      - 27017:27017
  mongorestore:
    build: mongo
    links:
      - mongodb
    depends_on:
      - mongodb
  

