version: "3.6"
services:
  smmdb-build:
    build:
      context: ./website
      dockerfile: DockerfileBuild
      args:
        - GOOGLE_CLIENT_ID
        - DISCORD_TOKEN
      cache_from:
        - tarnadas/smmdb-build
    image: tarnadas/smmdb-build
    working_dir: /usr/src/app
  smmdb-build-dep:
    build:
      context: ./website
      dockerfile: DockerfileBuildDep
      cache_from:
        - tarnadas/smmdb-build-dep
    image: tarnadas/smmdb-build-dep
    working_dir: /usr/src/app
  smmdb-api-build:
    build:
      context: ./api
      dockerfile: DockerfileBuild
      cache_from:
        - tarnadas/smmdb-api-build
    image: tarnadas/smmdb-api-build
