version: '3.6'
services:
  mongodb:
    image: mongo:3.4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodatabase:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    restart: always
volumes:
  mongodatabase:
networks:
  default:
    external:
      name: webproxy
